### PR TITLE
Added github stats and Contribution grap

### PR DESCRIPTION
**Pull request by annuv231**
I know its useless but looks cool on profile, I guess.

### CODE REVIEW

**Review by aparna2071 — APPROVED** [review]
Thanks for showing interest in my profile ❤️ 
Appreciate your efforts, thank you 👍

**Comment by VishwaS-22** [comment]
Hey @aparna2071! I visited your profile and came to know that your Contribution Graph is not visible. Please check with that because it might spoil your Profile! 
Screenshot (180)

Thankyou!

**Comment by aparna2071** [comment]
Hey @VishwaS-22 thanks a lot for pointing out this, will check 👍

**Comment by annuv231** [comment]
Hi @VishwaS-22  and @aparna2071 , This is because that api was hosted on heroku which stopped offering free services 😢 . I will udapte it once they move to different site, for reference posting that repo issue.

https://github.com/Ashutosh00710/github-readme-activity-graph/issues/166

**Pull request merged**
